# db settings
spring:
  # db settings for test
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Auto-update schema during development
    show-sql: true            # Show SQL logs for debugging
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

# logging settings
logging:
  level:
    root: INFO # less noisy than DEBUG
    com.example: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"