# db settings
spring:
  datasource:
    # need to set environment values
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Only validate, don't change schema -
    show-sql: false # Never log SQL in production (security issues)
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

# logging settings
logging:
  level:
    root: WARN
    com.example: INFO
  file:
    name: logs/myapp.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
