# port settings
server:
  port: 8080
# db settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Auto-update schema during development
    show-sql: true            # Show SQL logs for debugging
    properties:
      hibernate:
        format_sql: true

# logging settings
logging:
  level:
    com.example: DEBUG


