spring:
  profiles:
    active: dev
  application:
    name: discodeit
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

# common logging settings
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN